Phase 3: DATA CLEANING

In [1]:
#1. Importing Libraries
import pandas as pd
import numpy as np 

pd.set_option("display.max_columns", None)
pd.set_option("display.max_colwidth", None)

In [2]:
#2. Load the Dataset
df = pd.read_csv("final_reviews_dataset.csv")
print("Dataset Loaded Successfully!")
df.head()

Dataset Loaded Successfully!

,platform,review,rating,date,source
0,Cars24,The PDI tool turned my automobile acquiring journey fluid and worry free. The analysis statement was very deep.,5.0,2026-07-16,Google Play
1,Cars24,"Getting to buy a pre owned automobile via this application felt far more practical than outside hunting. .,",5.0,2026-07-16,Google Play
2,Cars24,"Getting to buy a vehicle turned out far simpler after utilizing this application frequently. The buy journey feels open the design is tidy and the entire experience is far more comfortable compared against old pathways .,",5.0,2026-07-16,Google Play
3,Cars24,"The PDI report explained every detail in a clear and simple manner.,",5.0,2026-07-16,Google Play
4,Cars24,"I enjoyed a fluid path because the buy journey felt safe and straightforward to grasp. .,",5.0,2026-07-16,Google Play

In [3]:
#3. dataset Information
print("Shape: " , df.shape)
df.info()
df.describe(include="all")

Shape:  (54499, 5)
<class 'pandas.DataFrame'>
RangeIndex: 54499 entries, 0 to 54498
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   platform  54499 non-null  str
 1   review    54498 non-null  str
 2   rating    54275 non-null  float64
 3   date      54499 non-null  str
 4   source    54499 non-null  str
dtypes: float64(1), str(4)
memory usage: 2.1 MB

,platform,review,rating,date,source
count,54499,54498,54275.000000,54499,54499
unique,2,54498,NaN,3293,2
top,Cars24,The PDI tool turned my automobile acquiring journey fluid and worry free. The analysis statement was very deep.,NaN,2020-08-17,Google Play
freq,45902,1,NaN,1073,54192
mean,NaN,NaN,3.271211,NaN,NaN
std,NaN,NaN,1.888916,NaN,NaN
min,NaN,NaN,1.000000,NaN,NaN
25%,NaN,NaN,1.000000,NaN,NaN
50%,NaN,NaN,5.000000,NaN,NaN
75%,NaN,NaN,5.000000,NaN,NaN
max,NaN,NaN,5.000000,NaN,NaN

In [4]:
#4: Check Missing Values
df.isnull().sum()

platform      0
review        1
rating      224
date          0
source        0
dtype: int64

In [5]:
#5: Check Duplicate Reviews
duplicates = df.duplicated(subset=["review"]).sum()
print("duplicate Reviews: ", duplicates)

duplicate Reviews:  0

In [6]:
#6: Remove Empty Reviews 
df.dropna(subset=["review"], inplace = True)

df = df[df["review"].str.strip() != ""]

df.isnull().sum()

platform      0
review        0
rating      224
date          0
source        0
dtype: int64

In [7]:
#7: Platform Names 

df["platform"] = df["platform"].str.strip().str.title()
df["platform"].value_counts()

platform
Cars24    45901
Spinny     8597
Name: count, dtype: int64

In [8]:
#8: Source Names
df["source"] = df["source"].str.strip().str.title()
df["source"].value_counts()

source
Google Play    54191
Trustpilot       307
Name: count, dtype: int64

In [9]:
#9: Convert Ratings 
df["rating"] = pd.to_numeric(df["rating"], errors = "coerce")
df["rating"] = df["rating"].fillna(0)
df["rating"] = df["rating"].astype(int)

In [10]:
df["rating"].value_counts().sort_index()

rating
0      224
1    20943
2     1381
3     1214
4     3485
5    27251
Name: count, dtype: int64

In [11]:
#10: Convert date

df["date"] = pd.to_datetime(df["date"], errors="coerce")

df["date"].head()

0   2026-07-16
1   2026-07-16
2   2026-07-16
3   2026-07-16
4   2026-07-16
Name: date, dtype: datetime64[us]

In [12]:
#11: Remove Invalid Rating

df = df[(df["rating"] >= 1) & (df["rating"] <= 5)]

df["rating"].value_counts().sort_index()

rating
1    20943
2     1381
3     1214
4     3485
5    27251
Name: count, dtype: int64

In [13]:
#12 Review length

df["review_length"] = df["review"].apply(len)

df["review_length"].describe()

count    54274.000000
mean       127.076114
std        127.701793
min          1.000000
25%         32.000000
50%         86.000000
75%        174.000000
max       3067.000000
Name: review_length, dtype: float64

In [ ]:
#13: Remove Very Short Reviews 

df = df[df["review_length"] > 5]
df.shape

(53379, 6)

In [15]:
#14: Final Data Summery 
print("Final Shape: ", df.shape)
df.head()

Final Shape:  (53379, 6)

,platform,review,rating,date,source,review_length
0,Cars24,The PDI tool turned my automobile acquiring journey fluid and worry free. The analysis statement was very deep.,5,2026-07-16,Google Play,111
1,Cars24,"Getting to buy a pre owned automobile via this application felt far more practical than outside hunting. .,",5,2026-07-16,Google Play,107
2,Cars24,"Getting to buy a vehicle turned out far simpler after utilizing this application frequently. The buy journey feels open the design is tidy and the entire experience is far more comfortable compared against old pathways .,",5,2026-07-16,Google Play,221
3,Cars24,"The PDI report explained every detail in a clear and simple manner.,",5,2026-07-16,Google Play,68
4,Cars24,"I enjoyed a fluid path because the buy journey felt safe and straightforward to grasp. .,",5,2026-07-16,Google Play,89

In [ ]:
#15: saving the final dataset

df.to_csv(
    "clean_reviews_dataset.csv",
    index=False,
    encoding="utf-8-sig"
)

print("Clean dataset saved successfully!")